import sys
from _typeshed import SupportsKeysAndGetItem, SupportsWrite, sentinel
from collections.abc import Hashable, Iterable, Iterator, Mapping, MutableSet, Set as AbstractSet, Sized
from typing import Any, Final, Generic, NoReturn, TypeAlias, TypeVar, overload
from typing_extensions import Self

from .anchor import Anchor
from .compat import MutableSliceableSequence, ordereddict
from .mergevalue import MergeValue
from .nodes import _ScalarNodeStyle
from .tag import Tag
from .tokens import CommentToken, _CommentGroup

__all__ = [
    "CommentedSeq",
    "CommentedKeySeq",
    "CommentedMap",
    "CommentedOrderedMap",
    "CommentedSet",
    "comment_attrib",
    "merge_attrib",
    "TaggedScalar",
    "C_POST",
    "C_PRE",
    "C_SPLIT_ON_FIRST_BLANK",
    "C_BLANK_LINE_PRESERVE_SPACE",
]

_Index: TypeAlias = int
_Key: TypeAlias = Hashable

_T = TypeVar("_T")
_D = TypeVar("_D")
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
_KT_co = TypeVar("_KT_co", covariant=True)
_VT_co = TypeVar("_VT_co", covariant=True)
_Commented = TypeVar("_Commented", bound=CommentedBase)

C_POST: Final = 0b00
C_PRE: Final = 0b01
C_SPLIT_ON_FIRST_BLANK: Final = 0b10
C_BLANK_LINE_PRESERVE_SPACE: Final = 0b100

comment_attrib: Final = "_yaml_comment"
format_attrib: Final = "_yaml_format"
line_col_attrib: Final = "_yaml_line_col"
merge_attrib: Final = "_yaml_merge"

class Comment:
    attrib: Final = comment_attrib
    comment: _CommentGroup | None
    # copilot: comments.py accepts the old-mode switch positionally and stores comment groups in fixed slots.
    def __init__(self, old: bool = True) -> None: ...
    @property
    def items(self) -> dict[_Index | _Key, _CommentGroup]: ...

    @property
    def end(self) -> list[CommentToken] | None: ...  # RTSC
    @end.setter
    def end(self, value: list[CommentToken] | None) -> None: ...  # RTSC

    @property
    def pre(self) -> list[CommentToken] | list[str] | None: ...  # RTSC
    @pre.setter
    def pre(self, value: list[CommentToken] | list[str] | None) -> None: ...  # RTSC

    # copilot: comments.py indexes each stored _CommentGroup by an integer position and returns its comment entry.
    def get(self, item: _Index | _Key, pos: int) -> CommentToken | list[CommentToken] | list[str] | None: ...  # RTSC
    def set(self, item: _Index | _Key, pos: int, value: CommentToken | list[CommentToken] | list[str] | None) -> None: ...  # RTSC
    def __contains__(self, x: str, /) -> bool: ...

class Format:
    attrib: Final = format_attrib
    # copilot: comments.py stores explicit flow style as True, False, or unset None.
    _flow_style: bool | None
    def __init__(self) -> None: ...
    def set_flow_style(self) -> None: ...
    def set_block_style(self) -> None: ...
    def flow_style(self, default: bool | None = None) -> bool | None: ...

class LineCol:
    attrib: Final = line_col_attrib
    line: int | None
    col: int | None
    data: dict[_Key, list[int]] | None
    def __init__(self) -> None: ...
    def add_kv_line_col(self, key: _Key, data: list[int]) -> None: ...
    def key(self, k: str, /) -> tuple[int, int] | None: ...
    def value(self, k: str, /) -> tuple[int, int] | None: ...
    def item(self, idx: int, /) -> tuple[int, int] | None: ...
    def add_idx_line_col(self, key: _Index, data: list[int]) -> None: ...

class CommentedBase:
    @property
    def ca(self) -> Comment: ...
    def yaml_end_comment_extend(self, comment: list[CommentToken] | None, *, clear: bool = False) -> None: ...
    def yaml_key_comment_extend(self, key: _Index | _Key, comment: _CommentGroup, *, clear: bool = False) -> None: ...
    def yaml_value_comment_extend(self, key: _Key, comment: _CommentGroup, *, clear: bool = False) -> None: ...
    def yaml_set_start_comment(self, comment: str, *, indent: int = 0) -> None: ...
    def yaml_set_comment_before_after_key(
        self, key: _Key, before: str | None = None, indent: int = 0, after: str | None = None, after_indent: int | None = None
    ) -> None: ...
    @property
    def fa(self) -> Format: ...
    def yaml_add_eol_comment(self, comment: str, key: _Index | _Key = sentinel, column: int | None = None) -> None: ...
    @property
    def lc(self) -> LineCol: ...
    @property
    def anchor(self) -> Anchor: ...
    def yaml_anchor(self) -> Anchor | None: ...
    def yaml_set_anchor(self, value: str, *, always_dump: bool = False) -> None: ...
    @property
    def tag(self) -> Tag: ...
    def yaml_set_ctag(self, value: Tag, /) -> None: ...
    def copy_attributes(self, t: _Commented, memo: dict[int, Any] | None = None) -> _Commented: ...

# copilot: comments.py combines same-type slicing from MutableSliceableSequence with list's concrete storage.
class CommentedSeq(MutableSliceableSequence[_T], list[_T], CommentedBase):  # type: ignore[misc]  # pyrefly: ignore [inconsistent-inheritance]
    def __getsingleitem__(self, idx: int) -> _T: ...
    def __setsingleitem__(self, idx: int, value: _T) -> None: ...
    def __delsingleitem__(self, idx: int) -> None: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Self: ...

class CommentedKeySeq(tuple[_T, ...], CommentedBase): ...

class CommentedMapView(Sized):
    def __init__(self, mapping: CommentedMap[Any, Any]) -> None: ...
    def __len__(self) -> int: ...

class CommentedMapKeysView(CommentedMapView, AbstractSet[_KT_co]):
    def __init__(self, mapping: CommentedMap[_KT_co, Any]) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[_KT_co]: ...

class CommentedMapItemsView(CommentedMapView, AbstractSet[tuple[_KT_co, _VT_co]]):
    def __init__(self, mapping: CommentedMap[_KT_co, _VT_co]) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __iter__(self) -> Iterator[tuple[_KT_co, _VT_co]]: ...

class CommentedMapValuesView(CommentedMapView, Generic[_VT_co]):
    def __init__(self, mapping: CommentedMap[Any, _VT_co]) -> None: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[_VT_co]: ...

class CommentedMap(ordereddict[_KT, _VT], CommentedBase):
    def insert(self, pos: int, key: _KT, value: _VT, comment: str | None = None) -> None: ...

    # copilot: comments.py accepts either a single key or a list of recursively traversed keys.
    @overload
    def mlget(self, key: _KT, default: _D | None = None, list_ok: bool = False) -> _VT | _D | None: ...
    @overload
    # copilot: recursive YAML values are intentionally dynamic, so the list-key form preserves the runtime Any boundary.
    def mlget(self, key: list[_Index | _Key], default: object | None = None, list_ok: bool = False) -> Any: ...

    def non_merged_items(self) -> Iterator[tuple[_KT, _VT]]: ...
    def keys(self) -> CommentedMapKeysView[_KT]: ...  # type: ignore[override]
    def values(self) -> CommentedMapValuesView[_VT]: ...  # type: ignore[override]
    def items(self) -> CommentedMapItemsView[_KT, _VT]: ...  # type: ignore[override]
    @property
    # copilot: constructor.py attaches the MergeValue container created while flattening YAML << merges.
    def merge(self) -> MergeValue | list[Self]: ...
    def add_referent(self, cm: Self) -> None: ...
    def add_yaml_merge(self, value: MergeValue) -> None: ...
    def update_key_value(self, key: _KT) -> None: ...

    @overload
    def get(self, key: _KT, default: None = None, /) -> _VT | None: ...
    @overload
    def get(self, key: _KT, default: _VT, /) -> _VT: ...
    @overload
    def get(self, key: _KT, default: _T, /) -> _VT | _T: ...

    @overload
    def pop(self, key: _KT) -> _VT: ...
    @overload
    def pop(self, key: _KT, default: _T) -> _VT | _T: ...

    # copilot: comments.py forwards mapping, pair-iterable, or keyword input to ordereddict.update.
    @overload
    def update(self, m: SupportsKeysAndGetItem[_KT, _VT], /) -> None: ...
    @overload
    def update(self, iterable: Iterable[tuple[_KT, _VT]], /) -> None: ...
    @overload
    def update(self: CommentedMap[str, _VT], m: SupportsKeysAndGetItem[str, _VT], /, **kw: _VT) -> None: ...
    @overload
    def update(self: CommentedMap[str, _VT], iterable: Iterable[tuple[str, _VT]], /, **kw: _VT) -> None: ...
    @overload
    def update(self: CommentedMap[str, _VT], /, **kw: _VT) -> None: ...

    def copy(self) -> Self: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Self: ...

class CommentedKeyMap(CommentedBase, Mapping[_KT, _VT]):
    # copilot: comments.py builds immutable mapping keys from ordereddict input but accepts its normal mapping forms.
    def __init__(self, *args: Mapping[_KT, _VT] | Iterable[tuple[_KT, _VT]], **kwargs: _VT) -> None: ...
    # copilot: these runtime aliases all call raise_immutable(*args, **kwargs), so object preserves their arbitrary failing calls.
    def __delitem__(self, *args: object, **kwargs: object) -> NoReturn: ...
    def __setitem__(self, *args: object, **kwargs: object) -> NoReturn: ...
    def clear(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pop(self, *args: object, **kwargs: object) -> NoReturn: ...
    def popitem(self, *args: object, **kwargs: object) -> NoReturn: ...
    def setdefault(self, *args: object, **kwargs: object) -> NoReturn: ...
    def update(self, *args: object, **kwargs: object) -> NoReturn: ...
    def __getitem__(self, index: _KT) -> _VT: ...
    def __iter__(self) -> Iterator[_KT]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...
    @classmethod
    # copilot: comments.py omits cls here, so bound calls pass the class as keys and raise TypeError.
    def fromkeys(cls, v: _VT | None = None) -> NoReturn: ...

class CommentedOrderedMap(CommentedMap[_KT, _VT]): ...

class CommentedSet(MutableSet[_T], CommentedBase):
    odict: ordereddict[_T, None]
    def __init__(self, values: Iterable[_T] | None = None) -> None: ...
    def add(self, value: _T) -> None: ...
    def discard(self, value: _T) -> None: ...
    def __contains__(self, x: object) -> bool: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...

class TaggedScalar(CommentedBase):
    value: str | None
    style: _ScalarNodeStyle | None
    def __init__(self, value: str | None = None, style: _ScalarNodeStyle | None = None, tag: Tag | str | None = None) -> None: ...
    def count(self, s: str, start: int | None = None, end: int | None = None) -> int: ...
    def __getitem__(self, pos: int | slice) -> str: ...

def dump_comments(d: object, name: str = "", sep: str = ".", out: SupportsWrite[str] = sys.stdout) -> None: ...
