from typing import Any, ClassVar, Final

merge_attrib: Final = "_yaml_merge"

class MergeValue:
    attrib: ClassVar[str]
    # copilot: constructor.py stores constructed YAML objects of arbitrary user types in this merge container.
    value: list[Any]
    sequence: Any | None
    merge_pos: int | None
    def __init__(self) -> None: ...
    def __getitem__(self, index: int | slice, /) -> Any: ...
    def __setitem__(self, index: int | slice, val: Any, /) -> None: ...
    def __len__(self) -> int: ...
    def append(self, elem: Any, /) -> None: ...
    def extend(self, elements: Any, /) -> None: ...
    def set_sequence(self, seq: Any, /) -> None: ...
