from collections.abc import Iterable
from typing import Any, Final

merge_attrib: Final[str]

# The upstream module leaves merge contents untyped because they vary by input shape.
class MergeValue:
    attrib: Final[str]
    value: list[Any]
    sequence: Any
    merge_pos: int | None
    def __init__(self) -> None: ...
    def __getitem__(self, index: Any, /) -> Any: ...
    def __setitem__(self, index: Any, val: Any, /) -> None: ...
    def __len__(self) -> int: ...
    def append(self, elem: Any, /) -> None: ...
    def extend(self, elements: Iterable[Any], /) -> None: ...
    def set_sequence(self, seq: Any, /) -> None: ...
